name: Build ModBox
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Cache Rust dependencies (Windows)
              uses: actions/cache@v3
              with:
                  path: |
                      ~\AppData\Local\cargo\registry
                      ~\AppData\Local\cargo\git
                      target\
                      src-tauri\target\
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'src-tauri/Cargo.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Cache Bun dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - uses: oven-sh/setup-bun@v2
            - name: Setup Env Vars
              run: echo "PUBLIC_FORGE_API=${{ secrets.PUBLIC_FORGE_API }}" >> .env

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install dependencies
              run: bun install

            - name: Build Tauri App
              run: bun run tauri build --debug

            - name: Upload Windows artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ModBox-windows
                  path: src-tauri/target/debug/bundle/msi/*.msi

    build-macos:
        runs-on: macos-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Cache Rust dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      src-tauri/target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Cache Bun dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - uses: oven-sh/setup-bun@v2

            - name: Setup Env Vars
              run: echo "VITE_FORGE_API=${{ secrets.VITE_FORGE_API }}" >> .env

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install dependencies
              run: bun install

            - name: Build Tauri App
              run: bun run tauri build

            - name: Upload macOS artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ModBox-macos
                  path: src-tauri/target/release/bundle/dmg/*.dmg

    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - name: Cache Rust dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      src-tauri/target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Cache Bun dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Setup Env Vars
              run: echo "VITE_FORGE_API=${{ secrets.VITE_FORGE_API }}" >> .env

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Install dependencies
              run: bun install

            - name: Build Tauri App
              run: bun run tauri build

            - name: Upload Linux artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ModBox-linux
                  path: src-tauri/target/release/bundle/deb/*.deb
